//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Info { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> Live { get; set; }
        public Nullable<bool> Visible { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
    }
}
